### ISSUE TITLE
An error occurred while creating a new user! (facebook login)

### ISSUE THREAD

**Issue by sandrodz** [miled/wordpress-social-login#263] opened 2018-05-03 13:41 UTC
Out of blue, FB login started showing error: `An error occurred while creating a new user!`

It appeared facebook modified profile url length, to fix this issue `user_url` can be changed to `varchar(255)`

<img width="992" alt="screen_shot_2018-05-03_at_4_54_53_pm" src="https://user-images.githubusercontent.com/8479569/39580010-23cfce0c-4ef9-11e8-992c-7e647a5b2fec.png">

But this is not a solution, plugin should be modified to use usermeta instead.

**Comment by samvthom16** [comment] 2018-05-04 16:14
@sandrodz I'm having the exact same issue on multiple sites. Do you have a temporary fix for this?

**Comment by sandrodz** [comment] 2018-05-04 16:55
@samvthom16 yes, modify user_url column in wp_users table from varchar 100 to 255.

**Comment by datdudejibril** [comment] 2018-06-08 11:37
![image](https://user-images.githubusercontent.com/25404256/41156177-c907910a-6aee-11e8-950c-582a530b255d.png)

I'm getting this error when doing so.

**Comment by williamay53** [comment] 2018-06-09 02:52
fixed!! thx very much

**Comment by phylaxis** [comment] 2018-06-14 00:11
Wow. Thanks for this fix. Is there any issue with exposing the URL that Facebook stores? I am using another plugin, WPforo and it displays the URL in the users profile.

**Comment by datdudejibril** [comment] 2018-06-14 20:51
If you run into the problem I had in the screenshot you have to disable strict mode in mysql.
The link below shows you how to do it in phpmyadmin
https://stackoverflow.com/questions/37964325/how-to-find-and-disable-mysql-strict-mode

**Comment by lastorset** [comment] 2018-07-27 07:18
@datdudejibril:
> Query error: \#1067 invalid default value for 'user_registered'

This might be an incorrect/outdated default in WordPress ([DATETIME is restricted to years 1000–9999 after MySQL 5.0.2](https://dev.mysql.com/doc/refman/8.0/en/datetime.html)). If you want to avoid disabling strict mode you can try

```sql
ALTER TABLE wp_users ALTER COLUMN user_registered SET DEFAULT '1000-01-01 00:00:00';
```

**Comment by vishnuaniyan** [comment] 2018-10-03 14:51
Thanks it worked..

**Comment by jimi008** [comment] 2018-11-09 18:29
> Out of blue, FB login started showing error: `An error occurred while creating a new user!`
> 
> It appeared facebook modified profile url length, to fix this issue `user_url` can be changed to `varchar(255)`
> 
> <img alt="screen_shot_2018-05-03_at_4_54_53_pm" width="992" src="https://user-images.githubusercontent.com/8479569/39580010-23cfce0c-4ef9-11e8-992c-7e647a5b2fec.png">
> 
> But this is not a solution, plugin should be modified to use usermeta instead.

Having same issue and I confirm that your solution fixed it for now. Waiting for permanent solution. Thanks 

@miled

**Comment by dcgavril** [comment] 2018-12-09 20:38
After the WordPress 5.0 update the user_url got changed back to 100 and just forgot about it and users could login using Facebook, and it seems that the change requested by someone it's not yet implemented in core https://core.trac.wordpress.org/ticket/34927 

Maybe we can add this check in the plugin before trying to create the user account and just update the database field instead of just failing to create the account (don't know how long it will take to get the patch approved in WordPress core).

**Comment by sandrodz** [comment] 2018-12-09 20:44
@dcgavril Only sane thing would be to just use `wp_usermeta` instead. I would do PR but I don't use this plugin, I was helping a friend debug the problem. In any case, if I have free time on my hands I will try to push the fix.

**Comment by cArkadiusz** [comment] 2019-01-07 13:22
@miled Could you address this issue? Why this url has changed?

**Comment by marlon-89** [comment] 2020-03-11 17:09
the problem is again relevant for some accounts, although I changed the length of "user_url"

**Closed** 2020-08-30 18:25 UTC
